#!/bin/bash
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║  Symmetric Key Analysis — Hardcoded Key Detection        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

DIR="$(cd "$(dirname "$0")" && pwd)"

echo "━━━ Extracted Key Metadata (via Frida dynamic instrumentation) ━━━"
cat "$DIR/des-keys.txt"
echo ""

echo "━━━ Key Analysis ━━━"
echo "  Key 1: [REDACTED]"
echo "    Type: Numeric string with special character prefix"
echo "    Entropy: ~1.75 bits/byte (ideal: 8.0)"
echo "    Verdict: Critically low entropy — trivially extractable"
echo ""
echo "  Key 2: [REDACTED]"
echo "    Type: English dictionary word (camelCase)"
echo "    Entropy: ~2.50 bits/byte (ideal: 8.0)"
echo "    Verdict: Critically low entropy — trivially extractable"
echo ""
echo "  Both keys are hardcoded ASCII strings embedded in the APK binary."
echo "  Standard reverse engineering tools (jadx, apktool) reveal them."
echo "  DES itself (56-bit) is brute-forceable in < 1 hour on FPGA."
echo ""
echo "  Conclusion: DES with hardcoded plaintext keys provides"
echo "  no meaningful cryptographic protection."
echo ""
echo "  Reproduction: Hook javax.crypto.Cipher.init() via Frida"
echo "  to capture key material at runtime."
